#!/bin/bash
set -euo pipefail
name="$(basename "$0")"
dir="$(dirname "$0")/.."
dest="${TMPDIR:-/tmp}/$name"
(cd "${dir}/cmd/happy" ; go build -trimpath -buildvcs=false -ldflags="-s -w -buildid=" -o "${dest}" .) && exec "${dest}" "$@"
